// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    // `npx prisma db seed` gọi seed E2E cục bộ (có cầu chì chỉ chạy trên
    // localhost/thien_duc_test). Production/CI vẫn dùng `npm run prisma:seed`.
    seed: 'node prisma/seed-e2e.js',
  },
  datasource: {
    url: process.env['DATABASE_URL'],
  },
});
